modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/MJRLegends/TileEntityLimiter/issues"
displayURL="https://minecraft.curseforge.com/projects/tileentitylimiter"
credits="MJRLegends for making the mod"
authors="MJRLegends"
[[mods]]
modId="tileentitylimiter"
version="1.0.0"
displayName="TileEntityLimiter"
description='''
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.tileentitylimiter]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"	

[[dependencies.tileentitylimiter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"